name: Tests
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  # Disable update notifications in CI
  NO_UPDATE_NOTIFIER: "1"
  # Set test mode for MCP Testing Framework
  MCP_TEST_MODE: "1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[ci]
        pip install pytest pytest-asyncio pytest-cov PyYAML
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=test_mcp --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install PyYAML types-PyYAML
    
    - name: Run ruff format check
      run: ruff format --check src/
    
    - name: Run ruff lint
      run: ruff check src/
    
    - name: Run mypy
      run: mypy src/test_mcp --ignore-missing-imports --no-site-packages
    
    - name: Run black check
      run: black --check src/